export const weatherCodes: Record<number, string> = {
  0: 'Clear Sky',
  1: 'Mainly clear',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing rime fog',
  51: 'Drizzle (light intensity)',
  53: 'Drizzle (moderate intensity)',
  55: 'Drizzle (heavy intensity)',
  56: 'Freezing drizzle (light intensity)',
  57: 'Freezing drizzle (heavy intensity)',
  61: 'Slight rain',
  63: 'Moderate rain',
  65: 'Heavy intensity rain',
  66: 'Freezing rain (light intensity)',
  67: 'Freezing rain (heavy intensity)',
  71: 'Snow (Slight intensity)',
  73: 'Snow (Moderate intensity)',
  75: 'Snow (Heavy intensity)',
  77: 'Snow grains',
  80: 'Rain showers (slight)',
  81: 'Rain showers (moderate)',
  82: 'Rain showers (violent)',
  85: 'Snow showers (slight)',
  86: 'Snow showers (heavy)',
  95: 'Thunderstorm (slight / moderate)',
  96: 'Thunderstorm (slight hail)',
  99: 'Thunderstorm (heavy hail)',
};
